language: node_js
node_js:
  - 10
cache: yarn
#script:
#  - yarn run build
deploy:
  provider: heroku
  api_key:
    secure: usXTJYb8E2peUQpVRxlH3paUvTZZ1XOZRXFhl4D4oX3Z3q8qPLGrL84tUI26h2Aasglc3SPAWkm4vWkVpN06vHso52jyVmMEcSx7zPbgWwe3UJNPvhwGRnFzND0061XIjfcbWgNroZmefhEJKOJ44PQK6nxSu+130J0HpOWREX/FxrT0SeABxWrLg55k/SHhAGtoeEzpeNT9dLE/DZPGouxUaGSDI3U3eUtfv9c3LqWJbCexDg9vNZ2+FCXOwQoGv8QR6j8D8zgXIeenoq2BfUCady7l4USSp+QBYu5nuTj/TA/ZlScJojKs628Ov7h17jD9gkyt1k4vBig27NxXh+wspL0AnFSj7VbtgVIPwTNHLZIJ4DdltJPCL6CEupLNvWTcGq9Ve7zddU/dBIz7aTNGObimcGSF4EE56pqWGCwk9MPVIfj8BCbFGtJtkjWIZzsrQ6Av48EIOYjrhz9LWfBNI5H0YW9vxdOD5t+5++3hn2zgIY6Vj3ZCRtYVgtAxpAFlmA3F9dypnFCK0x4cnlrQ712n27xlMbA/Xd6Zcf5x7g4wYXlwYz53WhDe0VPTQx5rwv7jnLnGDwe+9yLeLunBcC6Iv/WZYD8Qs/2j0cUMbYb17ZPmtxix44ZjVc2ShDhuILNWqHyROXdobGUcM7I/ZDLJg99d4ZjezOaznrQ=
  skip_cleanup: true
  app: f-disqus-core
  on:
    repo: Ilyaololo/f-disqus-core
