language: node_js
node_js:
  - 10
cache: yarn
deploy:
  provider: heroku
  api_key:
    secure: cnbC/mDpnBRtE2CUJX5JNBHAcdwHZe1G0tuACteI3dEUGyk+SpDJbBI7qMh5+xtVGeP6EqMdEkA5mOXBi3XER1DKDkW5l8gdULt59RVM1jfjttaCat0Abnu4u3z5LD2h6WV3qYtEp7GBue9KUlezOujOu5IUwrg7SUI0adNhSxUaHEe5EEi9IyGuRFDd/2JFiz7q3vYJ7XpS+X90ReJ/uX8sdnfX60TMZwP9jSVJpAqnj4iwSfnfAcsJewq/fKL62gdKo+/JgGOlFJe2pN5Z480wY5p5SnAmcB2BtW0RZ/PZXDZvoqwgLIpDYEjsw6RcN2y0Mw0bgByFCAZFqRiM4G1YeqdgVBNvtnS7xMyUQdshD9Fcm3uWcw/D9nSF65crNDhCXwjCkwZXxBZPx5Bs858sirK3kCIF2hvlhXDxL2e4jjDlpFxgdRkP/qx+UiPGfP6FXe3DK8MiBmFk5A4q12np0itDhTA4EXqhnxj09oYrhpACKtF2ZmBvWMrYOAqk3vHIoWUTDRb1hz8uFe4d8WDSCauMdE0Fy5GhTWrhlYh8TU2SEy8kMjfdkHZtN4Pk/bxv1L1XPyKN5VDUTlMlk6fbGYYLgJw5VVHojpa8CE0nkniE2/IVqIgF3nITRh6+eqBThwfnnjmrrwdoNh/21g9WDxJam3tQ84yryZIiui4=
  skip_cleanup: true
  app: f-disqus-core
  on:
    repo: Ilyaololo/f-disqus-core
